### ISSUE TITLE
generic water heater won't work after 2025.01 version

### ISSUE THREAD

**Issue by lpt2007** [dgomes/ha_generic_water_heater#9]
Hi,

integration not working after update ha to 2025.01

Here is error:
```
Logger: homeassistant.setup
Source: setup.py:497
First occurred: 19:14:35 (1 occurrences)
Last logged: 19:14:35

Unable to prepare setup for platform 'generic_water_heater.water_heater': Platform not found (cannot import name 'SUPPORT_OPERATION_MODE' from 'homeassistant.components.water_heater' (/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py)).
```

Here is warning:
Logger: homeassistant.setup
Source: setup.py:497
First occurred: 19:14:35 (1 occurrences)
Last logged: 19:14:35

Unable to prepare setup for platform 'generic_water_heater.water_heater': Platform not found (cannot import name 'SUPPORT_OPERATION_MODE' from 'homeassistant.components.water_heater' (/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py)).

Can you repair it?

thx in advance

**Comment by dgomes** [comment]
Hello!

I've just pushed a commit that should fix the issue, please give it a try :)

**Comment by lpt2007** [comment]
Hi, you didn't change version is still 0.0.3:) I try redownload but but it give me same error I supose redownload give me same version of py file. Can you change version? And then I give it a try again.

thx

**Comment by dgomes** [comment]
I see HACS removed the "beta version" that used to download directly from the main branch :(

Making a release...

**Comment by lpt2007** [comment]
Now is working. Big thanks:)

I must mention one thing, when I changing on/off my entity `switch.room_bath_boiler` the entity `water_heater.boiler` also go on/off, but when I changing on/off entity `water_heater.boiler` the entity `switch.room_bath_boiler` not go on/off.

**Comment by dgomes** [comment]
but the actual switch ? does it turn on ?

**Comment by lpt2007** [comment]
No. When I turn on water_heater.boiler switch switch.room_bath_boiler not turning on.

**Comment by lpt2007** [comment]
Hi, today I figured out that I still have same problem.  `water_heater.boiler` switch wont't turn on/off `switch.room_bath_boiler`, but `switch.room_bath_boiler` can turn on/off `water_heater.boiler`?

Why attribute of `water_heater.boiler` is `target_temp_high: null` and `target_temp_low: null`?

here is my configuration:
```
generic_water_heater:
  boiler:
    heater_switch: switch.room_bath_boiler
    temperature_sensor: sensor.room_bath_boiler_water_temperature
    target_temperature: 50
    delta_temperature: 5
```

![Image](https://github.com/user-attachments/assets/c3aadae6-f730-4901-b6bc-166a19db1200)
